
from melo_fwk.position_size_policies.base_size_policy import BaseSizePolicy
from melo_fwk.position_size_policies.vol_target_size_policy import VolTargetSizePolicy
from melo_fwk.position_size_policies.vol_target_discrete_size_policy import VolTargetDiscreteSizePolicy
from melo_fwk.position_size_policies.vol_target_inertia_policy import VolTargetInertiaPolicy
from melo_fwk.position_size_policies.vol_target import VolTarget
