
from melo_fwk.pose_size_vect.base_size_policy import BaseSizePolicy
from melo_fwk.pose_size_vect.vol_target_size_policy import VolTargetSizePolicy
from melo_fwk.pose_size_vect.vol_target_discrete_size_policy import VolTargetDiscreteSizePolicy
from melo_fwk.pose_size_vect.vol_target_inertia_policy import VolTargetInertiaPolicy
