
from melo_fwk.policies.size.base_size_policy import BaseSizePolicy
from melo_fwk.policies.size.vol_target_size_policy import VolTargetSizePolicy
from melo_fwk.policies.size.vol_target_discrete_size_policy import VolTargetDiscreteSizePolicy
from melo_fwk.policies.size.vol_target_inertia_policy import VolTargetInertiaPolicy
